name: dart_webrtc
description: Use the dart/js library to re-wrap the webrtc js interface of the browser, to adapted common browsers.
version: 0.2.3
homepage: https://github.com/flutter-webrtc/dart-webrtc

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  js: ^0.6.2
#  path: ^1.7.0
  source_gen: ^0.9.5

dev_dependencies:
  build_test: any
  build_runner: any
  build_web_compilers: any
  pedantic: ^1.9.0
  protoo_client: ^0.3.0
  http: any
  test: ^1.9.3
  js_wrapping_generator:
    path: ../dart-js-wrapping/js_wrapping_generator